---
# tasks file for forge_error_pages
- name: Ensure target directory
  file:
    path: /var/www
    owner: "{{ 'nginx' if target_webserver == 'nginx' else 'www-data' if ansible_os_family == 'Debian' else 'apache' }}"
    group: "{{ 'nginx' if target_webserver == 'nginx' else 'www-data' if ansible_os_family == 'Debian' else 'apache' }}"
    state: directory

- name: Upload error files
  unarchive:
    src: errors.tgz
    dest: /var/www/
    owner: "{{ 'nginx' if target_webserver == 'nginx' else 'www-data' if ansible_os_family == 'Debian' else 'apache' }}"
    group: "{{ 'nginx' if target_webserver == 'nginx' else 'www-data' if ansible_os_family == 'Debian' else 'apache' }}"
    creates: /var/www/errors

- name: Upload configuration for apache
  copy:
    src: apache.conf
    dest: "/etc/{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}/conf.d/forge_error_pages.conf"
  notify: restart apache
  when: target_webserver == 'apache'

- name: Upload configuration for nginx
  copy:
    src: nginx.conf
    dest: /etc/nginx/conf.d/forge_error_pages.conf
  notify: restart nginx
  when: target_webserver == 'nginx'
