---
# handlers file for forge_error_pages
- name: restart apache
  service:
    name: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
    state: restarted

- name: restart nginx
  service:
    name: nginx
    state: restarted
